name: Generate PCB Docs

on:
  push:
    paths:
      - 'kicad/**.kicad_pcb'
  workflow_dispatch:

jobs:
  kibot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        board_name: [left_half, right_half]
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: KiBot for ${{ matrix.board_name }}
        uses: INTI-CMNB/KiBot@v2_dk9
        with:
          board: 'kicad/${{ matrix.board_name }}.kicad_pcb'
          dir: 'Generated_Docs/${{ matrix.board_name }}'
          skip: schematic_check

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.board_name }}-gerbers
          path: 'Generated_Docs/${{ matrix.board_name }}'
